use_frameworks!

target 'CJSegmentController_Example' do
  pod 'CJSegmentController', :path => '../'

  target 'CJSegmentController_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
